version: '2.1'

services:

  kong-database:
    image: 'postgres:9.4'
    expose:
      - 5432
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - 'POSTGRES_USER=kong'
      - 'POSTGRES_DB=kong'
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "kong"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - default

  kong-migration:
    image: kong:0.11.2
    depends_on:
      kong-database:
        condition: service_healthy
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
    command: kong migrations up
    networks:
      - default

  kong:
    image: kong:0.11.2
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_ADMIN_LISTEN_SSL=0.0.0.0:8444
    ports:
      - '8000:8000'
      - '8443:8443'
    expose:
      - 8000
      - 8443
      - 8001
      - 8444
      - 7946
      - 7373
    depends_on:
      kong-database:
        condition: service_healthy
      kong-migration:
        condition: service_started
    networks:
      - default
      
  kong-dashboard:
    image: pgbi/kong-dashboard:v3.0.1
    expose:
      - 8080
    ports:
      - 8080:8080
    command: 'start --kong-url http://kong:8001 --basic-auth user=pwd'
    depends_on:
      - kong
    restart: always
    networks:
      - default

networks: 
  default:
